//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }


  /// This `_R.color` struct is generated, and contains static references to 1 colors, and 1 namespaces.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
    var operationColor: operationColor { .init(bundle: bundle) }

    func operationColor(bundle: Foundation.Bundle) -> operationColor {
      .init(bundle: bundle)
    }


    /// This `_R.color.operationColor` struct is generated, and contains static references to 3 operationColors.
    struct operationColor {
      let bundle: Foundation.Bundle

      /// Color `OperationColor/Clear`.
      var clear: RswiftResources.ColorResource { .init(name: "OperationColor/Clear", path: ["OperationColor"], bundle: bundle) }

      /// Color `OperationColor/Number`.
      var number: RswiftResources.ColorResource { .init(name: "OperationColor/Number", path: ["OperationColor"], bundle: bundle) }

      /// Color `OperationColor/Test`.
      var test: RswiftResources.ColorResource { .init(name: "OperationColor/Test", path: ["OperationColor"], bundle: bundle) }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launch: launch { .init(bundle: bundle) }

    func launch(bundle: Foundation.Bundle) -> launch {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launch.validate()
    }


    /// Storyboard `Launch`.
    struct launch: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "Launch"
      func validate() throws {

      }
    }
  }
}